# Generated by Django 2.2.3 on 2019-10-23 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.FileField(default=datetime.datetime(2019, 10, 23, 22, 13, 59, 877180, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
